name: Run Analysis Workflow

on:
  # 触发Workflow的事件，比如push、pull_request等
  push:
    branches:
      - main  # 指定触发的分支

jobs:
  analyze:
    runs-on: ubuntu-latest  # 使用Ubuntu最新镜像作为运行环境

    env:
      EN_FILE: 'input_data/en_book.txt'  # 定义环境变量
      CN_FILE: 'input_data/cn_book.txt'
      OUTPUT_FILE: 'output/output.srt'
      VTT_FILE: 'input_data/sub.vtt'
      HTML_FILE: 'output/diff.html'
      GET_EMBEDDINGS_FROM_FILE: 'false'  # 字符串形式的布尔值，因为环境变量默认为字符串类型

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 检出代码到工作目录

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # 或您需要的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 假设您的依赖在requirements.txt文件中

    - name: Run Python Script with Env Variables
      run: |
        python your_script.py \
          --en-file ${{ env.EN_FILE }} \
          --cn-file ${{ env.CN_FILE }} \
          --output-file ${{ env.OUTPUT_FILE }} \
          --vtt-file ${{ env.VTT_FILE }} \
          --html-file ${{ env.HTML_FILE }} \
          --get-embeddings-from-file ${{ env.GET_EMBEDDINGS_FROM_FILE }}
